### ISSUE TITLE
[New Feature]: adding preloader

### ISSUE THREAD

**Issue by solanki505** [ChromeGaming/Formation-Absent#25]
### 🎮 feature Request

feature logic and basic description
appears on a web page while its content is being loaded

### Point down the features

feature points
1.User Experience Enhancement
2.Customization
3.Responsive Interaction
4.making page more interactive 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by 143divya** [comment]
Can you please this issue to me under GssoC24?
