### ISSUE TITLE
Missing learn.md_[Documentation Bug]: 

### ISSUE THREAD

**Issue by Meetjain1** [ChromeGaming/Formation-Absent#30]
### Describe the bug ✍️

Learn.md file is missing in our current repository.

@roy7077 assign this issue to me I will create it 

### Provide step by step information reproduce the bug 📄

A learn.md file in GitHub is often used as a documentation file to provide learning resources, instructions, or a guide to help users understand how to use the repository or learn specific concepts related to the project. It's similar to a README.md but specifically focused on educational content. Below is a detailed guide on how to create and use a learn.md file in a GitHub repository.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Meetjain1** [comment]
@Durgesh4993 have a look on the pr #45 to close this issue

**Comment by Gokilp** [comment]
please assign me this issue...

**Comment by Durgesh4993** [comment]
@Gokilp issue is already assigned

**Comment by Gokilp** [comment]
Thank you
