### ISSUE TITLE
Adding a logo

### ISSUE THREAD

**Issue by samridhi171** [ChromeGaming/Formation-Absent#34]
We can add a logo to the website. I have experience with designing. Please design it to me under Gssoc.

**Comment by Durgesh4993** [comment]
@samridhi171 Have you any design

**Comment by Gokilp** [comment]
please assign me this issue...

**Comment by samridhi171** [comment]
> @samridhi171 Have you any design
I can make a few and send them to you! I can try something pixelated. like the theme of the game.
