### ISSUE TITLE
[Enhancement]: Center Text alignment

### ISSUE THREAD

**Issue by Rags-Mishra** [ChromeGaming/Formation-Absent#40]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The game's main screen after beginning the game has a text that is probably a heading describing the game's stage or level. It has multiple icons too. The text is in the center of the screen which makes rest of the text not clearly visible. 

Here's an image.
![image](https://github.com/ChromeGaming/Formation-Absent/assets/83007531/14708fc8-52ef-48c8-ac93-d54774b25eac)

### Describe the solution you'd like

- The heading's position is to be finalized that whether it is supposed to be in the center.
- If it is to be centered at the top or bottom, the code has to modified accordingly.
- Second step is to be checked for all screens where the said text is visible.

***Kindly assign this issue to me under GSSOC'24*** :computer: 
***Thank you!*** :bow: 

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Rags-Mishra Please raise any other issue, because someone is already working on it
