### ISSUE TITLE
[Bug]: Footer social icons are not responsive

### ISSUE THREAD

**Issue by DishaSethi** [ChromeGaming/Formation-Absent#49]
### Give a brief about the bug ✍️

Description: The social icons are not responsive in the footer..... they are overlapping and also disappearing after a while when the size is decreased.
![Screenshot (625)](https://github.com/ChromeGaming/Formation-Absent/assets/142926792/9966248c-88f1-4e9e-b4a6-36c6d155835e)

### What is the expected behavior? 🤔

Description: They should not overlap and also on decreasing the size they should remain aligned at the bottom .

### Provide step by step information reproduce the bug 📄

Description: I will fix this by changing the footer css and by adding media queries in the footer to make it more responsive and well aligned and visible .
Please assign this issue to me , I am a GSSOC contributor.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Kartikk1820** [comment]
Assign this issue to me I am from GSSoC'24

**Comment by roy7077** [comment]
@DishaSethi assigning this issue to you,

**Comment by Gokilp** [comment]
please assign me this issue...

**Comment by Kartikk1820** [comment]
> @DishaSethi when  I get my batch or reward
