### ISSUE TITLE
[New Feature]:  add discord logo

### ISSUE THREAD

**Issue by jayanththalla** [ChromeGaming/Formation-Absent#52]
### 🎮 feature Request

adding discord logo to the footer and hover it

### Select program in which you are contributing
gssoc
please assign me @pa 
### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Gokilp** [comment]
please assign me this issue...

**Comment by roy7077** [comment]
@jayanththalla assigning this issue to you, Go ahead
