### ISSUE TITLE
[New Feature]: adding amodal feedback form in home page

### ISSUE THREAD

**Issue by solanki505** [ChromeGaming/Formation-Absent#56]
### 🎮 feature Request

feature logic and basic description
Describe the feature
feedback is important feature to know the suggestion of the users, using this site.
example clicking on the cloud icon feedback page will pop out
![Screenshot 2024-06-07 112601](https://github.com/ChromeGaming/Formation-Absent/assets/158484284/bad47dc3-0c41-4b6d-b903-3497abd2b2b4)

### Point down the features

feature points
Describe the solution you'd like
I would like to add a feedback icon in the home page section which will pop out a feedback form.Users playing this game can put their feedback and star rating 
Describe alternatives you've considered
adding modal feedback form
Please assign me this 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by roy7077** [comment]
@solanki505 assigning this issue to you , Go ahead

**Comment by roy7077** [comment]
@solanki505 assigning this issue to you , Go ahead
