### ISSUE TITLE
[New Feature]: Mouse moving glowing effect

### ISSUE THREAD

**Issue by namandude** [ChromeGaming/Formation-Absent#57]
### 🎮 feature Request

I will add the glowing effect where ever mouse moves in the screen giving the webiste another level of looks . 

### Point down the features

![image](https://github.com/ChromeGaming/Formation-Absent/assets/118013565/f7e0998f-e3e3-4b82-8f6a-200bcc6cb217)

Like that  but i will change the color according to this website . 
Please assign me this under Gssoc. I would like to contribute in this.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by roy7077** [comment]
@namandude assigning this issue to you
